### ISSUE TITLE
Error: Could not find "stylelint-use-logical-spec". Do you need a `configBasedir`?

### ISSUE THREAD

**Issue by smaboshe** [thoughtbot/design-system#265]
Hound is reporting the following error:
```
Error: Could not find "stylelint-use-logical-spec". Do you need a `configBasedir`?
    at module.exports (/home/linters/app/versions/stylelint-10.1.0/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at getModulePath (/home/linters/app/versions/stylelint-10.1.0/node_modules/stylelint/lib/utils/getModulePath.js:26:11)
    at /home/linters/app/versions/stylelint-10.1.0/node_modules/stylelint/lib/augmentConfig.js:123:14
    at Array.map ()
    at absolutizePaths (/home/linters/app/versions/stylelint-10.1.0/node_modules/stylelint/lib/augmentConfig.js:122:48)
    at /home/linters/app/versions/stylelint-10.1.0/node_modules/stylelint/lib/augmentConfig.js:32:14
    at async Promise.all (index 0)
```

e.g. https://github.com/thoughtbot/design-system/pull/264#pullrequestreview-1623893280

Ref:
- https://hub.thoughtbot.com/handbook/playbook/developing/style-guide.md

**Comment by mo-amama** [comment]
Author can't remember what this was about, we will be closing it for now.
